# Generated by Django 5.2.7 on 2025-11-01 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=100)),
                ('objetivo', models.TextField()),
                ('herramienta', models.CharField(max_length=50)),
                ('publico_objetivo', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
