# Generated by Django 5.2.7 on 2025-11-05 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_accion', models.CharField(max_length=100)),
                ('detalle_accion', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(max_length=100)),
                ('ubi_institucion', models.CharField(max_length=100)),
                ('institucion_descripcion', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateField()),
                ('hora_reporte', models.IntegerField()),
                ('estado_reporte', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatTipoAcoso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acoso_nombre', models.CharField(max_length=100)),
                ('descripcion_acoso', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Victima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vict_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('vict_apellido_m', models.CharField(blank=True, max_length=100, null=True)),
                ('vict_apellido_p', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cat_accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.cataccion')),
                ('cat_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.catinstitucion')),
                ('cat_reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.catreporte')),
                ('cat_tipo_acoso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.cattipoacoso')),
            ],
        ),
        migrations.AddField(
            model_name='catreporte',
            name='victima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.victima'),
        ),
    ]
