# Generated by Django 5.2.7 on 2025-12-05 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_institucion_tip_tipoacoso_reporte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='cat_accion',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='cat_institucion',
        ),
        migrations.RemoveField(
            model_name='catreporte',
            name='victima',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='cat_reporte',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='cat_tipo_acoso',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AlterModelOptions(
            name='reporte',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
        migrations.AlterModelOptions(
            name='tip',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Consejo', 'verbose_name_plural': 'Consejos de Seguridad'},
        ),
        migrations.AlterModelOptions(
            name='tipoacoso',
            options={'verbose_name': 'Tipo de Acoso', 'verbose_name_plural': 'Glosario de Acosos'},
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='estado',
        ),
        migrations.AddField(
            model_name='reporte',
            name='status',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('revision', 'En Revisión'), ('proceso', 'En Proceso'), ('cerrado', 'Cerrado')], default='nuevo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institucion',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre de la Institución'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas adicionales'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='correo_reportante',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción de los hechos'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='nombre_reportante',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='telefono_reportante',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='tipoacoso',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción o Definición'),
        ),
        migrations.AlterField(
            model_name='tipoacoso',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del tipo'),
        ),
        migrations.DeleteModel(
            name='CatAccion',
        ),
        migrations.DeleteModel(
            name='CatInstitucion',
        ),
        migrations.DeleteModel(
            name='Victima',
        ),
        migrations.DeleteModel(
            name='CatReporte',
        ),
        migrations.DeleteModel(
            name='CatTipoAcoso',
        ),
        migrations.DeleteModel(
            name='Denuncia',
        ),
    ]
