# Generated by Django 5.2.7 on 2026-03-10 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_reporte_correo_reportante_alter_reporte_lugar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='llamar_911',
            field=models.BooleanField(default=False, verbose_name='Solicitó contacto urgente'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='nivel_urgencia',
            field=models.CharField(choices=[('critico', 'Crítico'), ('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo / Informativo')], default='medio', max_length=10, verbose_name='Nivel de urgencia'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='revisado',
            field=models.BooleanField(default=False, verbose_name='Revisado por admin'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='revisado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_revisados', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
        migrations.CreateModel(
            name='MensajeAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('es_del_admin', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='projects.reporte')),
            ],
            options={
                'verbose_name': 'Mensaje del Admin',
                'verbose_name_plural': 'Mensajes Admin',
                'ordering': ['creado_en'],
            },
        ),
    ]
