"""
Django settings for proyecto_acoso project.

Generated by 'django-admin startproject' using Django 5.2.7.

Configuración completa para Portal Seguro / Sentinel v9.0
Autor: Proyecto Sentinel
Versión: 9.0
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Cargar variables de entorno desde archivo .env en la raíz
load_dotenv()

# ============================================
# CONFIGURACIÓN DE PYMYSQL (MySQL para Windows)
# ============================================

import pymysql
pymysql.install_as_MySQLdb()

# Base directory del proyecto
BASE_DIR = Path(__file__).resolve().parent.parent

# ============================================
# SEGURIDAD Y CONFIGURACIÓN BÁSICA
# ============================================

SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-!l)_)psc#sf^-0cpe-aw4@6(238-g%!z1tqbk=tip+wc%*hjpi'
)

DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.railway.app',
    '.up.railway.app',
    '.onrender.com',                                # ← NUEVO: Render.com
    'semiexclusively-bactericidal-evangeline.ngrok-free.dev',
    os.getenv('RAILWAY_PUBLIC_DOMAIN', ''),
    os.getenv('RENDER_EXTERNAL_HOSTNAME', ''),      # ← NUEVO: hostname auto de Render
    'tudominio.com',
    'www.tudominio.com',
]

# Orígenes confiables para CSRF
CSRF_TRUSTED_ORIGINS = [
    'https://semiexclusively-bactericidal-evangeline.ngrok-free.dev',
    'https://*.railway.app',
    'https://*.up.railway.app',
    'https://*.onrender.com',                       # ← NUEVO: Render HTTPS
    'https://tudominio.com',
    'https://www.tudominio.com',
]

# ============================================
# AUTENTICACIÓN Y REDIRECCIÓN
# ============================================

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# ============================================
# CONFIGURACIÓN DE EMAIL (DESARROLLO)
# ============================================

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'

# ============================================
# APLICACIONES INSTALADAS
# ============================================

INSTALLED_APPS = [
    # Apps propias del proyecto
    "pages.apps.PagesConfig",
    "accounts",
    'projects.apps.ProjectsConfig',

    # Apps de Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps adicionales
    'crispy_forms',
    'crispy_bootstrap5',
]

# ============================================
# MIDDLEWARE
# ============================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',   # sirve íconos PWA y estáticos
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ============================================
# CONFIGURACIÓN DE URLS
# ============================================

ROOT_URLCONF = 'proyecto_acoso.urls'

# ============================================
# TEMPLATES
# ============================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'proyecto_acoso.wsgi.application'

# ============================================
# BASE DE DATOS - MySQL Local
# ============================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'acoso_sexual_ae',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
    }
}

# ============================================
# VALIDACIONES DE CONTRASEÑA
# ============================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ============================================
# INTERNACIONALIZACIÓN
# ============================================

LANGUAGE_CODE = 'es-mx'
TIME_ZONE = 'America/Mexico_City'
USE_I18N = True
USE_TZ = True

# ============================================
# ARCHIVOS ESTÁTICOS Y MEDIA
# ============================================

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static'] if os.path.exists(BASE_DIR / 'static') else []

# WhiteNoise comprime y sirve estáticos en producción
# IMPORTANTE: Los íconos PWA en static/icons/ se sirven automáticamente
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_ROOT = BASE_DIR / 'uploads'
MEDIA_URL = 'media/'

# ============================================
# TIPO DEFAULT PARA CLAVE PRIMARIA
# ============================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================
# CONFIGURACIÓN DE SEGURIDAD (PRODUCCIÓN)
# ============================================

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# ============================================
# CONFIGURACIÓN DE SESIONES
# ============================================

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 86400
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = not DEBUG

# ============================================
# CONFIGURACIÓN DE LOGGING
# ============================================

logs_dir = BASE_DIR / 'logs'
if not logs_dir.exists():
    logs_dir.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
        'sentinel_file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'sentinel_ai.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'sentinel_ai': {
            'handlers': ['console', 'sentinel_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'sentinel_ai_views': {
            'handlers': ['console', 'sentinel_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ============================================
# CONFIGURACIÓN DE BLACKNOX AI
# ============================================

BLACKNOX_API_KEY     = os.getenv('BLACKNOX_API_KEY', '')
BLACKNOX_BASE_URL    = os.getenv('BLACKNOX_BASE_URL', 'https://api.blacknovo.com/v1')
BLACKNOX_MODEL       = os.getenv('BLACKNOX_MODEL', 'gpt-4o')
BLACKNOX_MAX_TOKENS  = int(os.getenv('BLACKNOX_MAX_TOKENS', '1500'))
BLACKNOX_TEMPERATURE = float(os.getenv('BLACKNOX_TEMPERATURE', '0.7'))
BLACKNOX_TIMEOUT     = int(os.getenv('BLACKNOX_TIMEOUT', '60'))

# ============================================
# CONFIGURACIÓN DE CACHÉ
# ============================================

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-sentinel-cache',
    }
}

# ============================================
# CONFIGURACIÓN DE CRISPY FORMS
# ============================================

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"